version: '3.9'
services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #   - "8080:6633"
  #   networks:
  #     sdn:
  #       ipv4_address: 172.16.0.6
  # web1:
  #       image: strm/helloworld-http
  #       networks:
  #         sdn:
  #           ipv4_address: 172.16.0.100
  # web2:
  #       image: strm/helloworld-http
  #       networks:
  #         sdn:
  #           ipv4_address: 172.16.0.101   
  # web3:
  #       image: strm/helloworld-http
  #       networks:
  #         sdn:
  #           ipv4_address: 172.16.0.102        
  opendaylight_max:  
    build:
      context: .
      dockerfile: opendaylight/Dockerfile
    tty: true
    networks:
      sdn:
    deploy:
      replicas: 3
    # ports:
    #   - 6633:6633
    #   - 8181:8181
    #   - 8101:8101
    # expose:
    #   - 6633
    #   - 8181
    #   - 8101

  # opendaylight1:  
  #   build:
  #     context: .
  #     dockerfile: opendaylight/Dockerfile
  #     args:
  #       - cluster_number=1
  #   tty: true
  #   networks:
  #     sdn:
  #       ipv4_address: 172.19.0.2
  #   ports:
  #     - 6633:6633
  #     - 8181:8181
  #     - 8101:8101
  # opendaylight2: 
  #   build:
  #     context: .
  #     dockerfile: opendaylight/Dockerfile
  #     args:
  #       - cluster_number=2
  #   tty: true
  #   networks:
  #     sdn:
  #      ipv4_address: 172.19.0.3
  #   ports:
  #     - 6634:6633
  #     - 8182:8181
  #     - 8102:8101
  # opendaylight3:
  #   build:
  #     context: .
  #     dockerfile: opendaylight/Dockerfile
  #     args:
  #       - cluster_number=3
  #   tty: true
  #   networks:
  #     sdn:
  #      ipv4_address: 172.19.0.4
    # ports:
    #   - 6635:6633
    #   - 8183:8181
    #   - 8103:8101
  # mininet:  
  #    build:
  #      context: .
  #      dockerfile: mininet/Dockerfile
  #    tty: true
  #    networks:
  #      sdn:
  #       ipv4_address: 172.16.0.222
  #    privileged: true
  #    volumes:
  #      - ./mininet/scenarios:/scenarios:delegated
  # portainer:
  #    image: portainer/portainer-ce:latest
  #    container_name: portainer
  #    security_opt:
  #      - no-new-privileges:true
  #    volumes:
  #      - /etc/localtime:/etc/localtime:ro
  #      - /var/run/docker.sock:/var/run/docker.sock:ro
  # #      - ./portainer-data:/data
  #    ports:
  #     - 9000:9000
  #    networks:
  #      sdn:

networks:
  sdn:
    ipam:
      config:
       - subnet: 172.16.0.0/16
# volumes:
#   postgres:
#     driver: local
#   redis:
#     driver: local
#   rabbit-data:
#     driver: local
