version: '3.5'
services:
  # nginx:
    # build: ./nginx
    # ports:
    # - "8080:6633"
    # networks:
    #   sdn:
    #     ipv4_address: 172.16.0.6
  # opendaylight_max:  
  #   build: opendaylight/
  #   tty: true
  #   networks:
  #     sdn:
  #   deploy:
  #     replicas: 3
  #   ports:
  #   - "6633:6633"
  opendaylight_max_1:  
    build: opendaylight/
    tty: true
    networks:
      sdn:
    ports:
      - 6633:6633
      - 6653:6653
      - 8181:8181
      - 8101:8101
  opendaylight_max_2:  
    build: opendaylight/ 
    tty: true
    networks:
      sdn:
    ports:
      - 6634:6633
      - 6654:6653
      - 8182:8181
      - 8102:8101
  opendaylight_max_3:  
    build: opendaylight/
    tty: true
    networks:
      sdn:
    ports:
      - 6635:6633
      - 6655:6653
      - 8183:8181
      - 8103:8101
    # ports:
      # - "8000:8000"
 # mininet:  
  #    build:
  #      context: .
  #      dockerfile: mininet/Dockerfile
  #    tty: true
  #    networks:
  #      sdn:
  #       ipv4_address: 172.16.0.222
  #    privileged: true
  #    volumes:
  #      - ./mininet/scenarios:/scenarios:delegated
networks:
  sdn:
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #   - subnet: 172.16.0.0/24
    # driver: "overlay"
    #   - internal: false
    # ipam:
    #   config:
    #    - subnet: 192.168.0.8/29
# networks:
#   default:
#     external:
#       name: nginx-proxy