version: '3.9'
services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #   - "8080:6633"
  #   networks:
  #     sdn:
  #       ipv4_address: 172.19.0.6
  opendaylight1:  
    build:
      context: .
      dockerfile: opendaylight/Dockerfile
      args:
        - cluster_number=1
    tty: true
    networks:
      sdn:
        ipv4_address: 172.19.0.2
    ports:
      - 6633:6633
      - 8181:8181
      - 8101:8101
  opendaylight2: 
    build:
      context: .
      dockerfile: opendaylight/Dockerfile
      args:
        - cluster_number=2
    tty: true
    networks:
      sdn:
       ipv4_address: 172.19.0.3
    ports:
      - 6634:6633
      - 8182:8181
      - 8102:8101
  opendaylight3:
    build:
      context: .
      dockerfile: opendaylight/Dockerfile
      args:
        - cluster_number=3
    tty: true
    networks:
      sdn:
       ipv4_address: 172.19.0.4
    ports:
      - 6635:6633
      - 8183:8181
      - 8103:8101
  mininet:  
    depends_on:
      - opendaylight1
      # - opendaylight2
      # - opendaylight3
    build:
      context: .
      dockerfile: mininet/Dockerfile
    tty: true
    networks:
      sdn:
       ipv4_address: 172.19.0.5
    privileged: true
    volumes:
      - ./mininet/net.py:/net.py:delegated
networks:
  sdn:
    driver: bridge
    ipam:
      config:
       - subnet: 172.19.0.0/16
# volumes:
#   postgres:
#     driver: local
#   redis:
#     driver: local
#   rabbit-data:
#     driver: local
